from typing import List

from pydantic import BaseModel, Field, conint


# 1. Schema for incoming Query Requests
class QueryRequest(BaseModel):
    # Enforce that query cannot be empty or just whitespaces
    query: str = Field(
        ..., min_length=1, description="The Hindi, Hinglish, or English search query"
    )
    # Enforce that top_k must be an integer between 1 and 10 to protect DB performance
    top_k: conint(ge=1, le=10) = Field(default=3, description="Maximum number of relevant chunks to retrieve")  # type: ignore


# 2. Schema for representing source attribution inside the query response
class SourceDocumentInfo(BaseModel):
    source_file: str = Field(..., description="The name of the source PDF manual")
    page_number: int = Field(
        ..., description="The page number where the fact was found"
    )


# 3. Schema for outgoing Query Responses
class QueryResponse(BaseModel):
    query: str = Field(..., description="The original query submitted by the user")
    answer: str = Field(
        ..., description="The grounded Hinglish/Hindi response generated by the LLM"
    )
    sources: List[SourceDocumentInfo] = Field(
        default_factory=list,
        description="List of source files and page numbers used as context",
    )


# 4. Schema for outgoing Health Check Responses
class HealthCheckResponse(BaseModel):
    status: str = Field(
        default="healthy", description="Current status of the API server"
    )
    qdrant_connected: bool = Field(
        ..., description="Whether the API can successfully communicate with Qdrant"
    )
    version: str = Field(
        default="0.1.0", description="The current version of the RAG pipeline"
    )
